# Operação Nova Chance

**Disciplina:** Ciência de Dados com Python  
**Instituição:** Inatel – Instituto Nacional de Telecomunicações  
**Prof. Ruan Patrick de Souza**

---

> *"Ninguém escolhe a vida de mendigo... mas todo mundo pode escolher aproveita novas chances."*  
> — Zé das Couves, filósofo de calçada

**Instruções:**
- Preencha as células de código onde indicado.
- Não altere as células de setup.
- Esta lista cobre **NumPy** e **Pandas**.

### Setup Inicial
Execute esta célula antes de começar. O Zé preparou o ambiente.

In [2]:
import numpy as np
import pandas as pd

print("Ambiente carregado! Vamos lá, segunda chance ativada!")

Ambiente carregado! Vamos lá, segunda chance ativada!


# **Bloco 1 — NumPy**

### Questão 1 – Controle de Doações em Array

O albergue recebeu doações de alimentos (em kg) durante **10 dias consecutivos**. Use `np.random.seed(42)` e crie um array de **10 números aleatórios inteiros entre 5 e 50** representando os kg doados por dia.

**a)** Exiba as propriedades `size`, `ndim` e `shape` do array;  
**b)** Calcule e exiba a **média**, o **mínimo** e o **máximo** de doações diárias;  
**c)** Mostre o **índice do dia** com maior doação e o **índice do dia** com menor doação;  
**d)** Mostre quantos dias tiveram doação **acima da média**.

In [ ]:
# Questão 1
np.random.seed(42)
doacoes = np.random.randint(5, 51, size=10)

print("Array de doações (kg):", doacoes)

# a) Propriedades do array
print(doacoes.size)
print(doacoes.ndim)
print(doacoes.shape)

# b) Média, mínimo e máximo
print("Média:", doacoes.mean())
print("Mínimo:", doacoes.min())
print("Máximo:", doacoes.max())


# c) Índice do maior e menor dia de doação
print(f"Índice do maior dia de doação:{doacoes.argmax()}")
print(f"Índice do menor dia de doação: {doacoes.argmin()}")


# d) Quantidade de dias com doação acima da média
media_doacoes = doacoes.mean()
dias_acima_media = (doacoes > media_doacoes).sum()
print(f"Quantidade de dias com doação acima da média: {dias_acima_media}")

Array de doações (kg): [43 33 19 47 12 25 43 23 27 15]
10
1
(10,)
Média: 28.7
Mínimo: 12
Máximo: 47
Índice do maior dia de doação:3
Índice do menor dia de doação: 4
Quantidade de dias com doação acima da média: 4 babababa


### Questão 2 – Mapa do Albergue e Seleção de Candidatos

**Parte A — Mapa do Albergue**

O gestor do albergue quer visualizar a ocupação dos **12 quartos** em formato de planta. Crie um array com os valores de **1 a 12** e:

**a)** Remodelar (`reshape`) para uma **matriz 3x4** (3 andares, 4 quartos por andar);  
**b)** Exibir a **soma de cada andar** (linha) e a **soma de cada coluna de quartos**.

---

**Parte B — Seleção para Capacitação**

O CRAS possui um programa de capacitação profissional. Para participar, o candidato precisa ter **IDH de bairro >= 0.65** e **ter menos de 45 anos**. Use os arrays abaixo:

```python
nomes    = np.array(["Zé", "Maria", "Cláudio", "Lurdes", "Expedito", "Raimundo", "Fátima", "Tonho"])
idades   = np.array([38, 52, 41, 29, 47, 33, 61, 44])
idh      = np.array([0.71, 0.58, 0.80, 0.63, 0.70, 0.75, 0.55, 0.68])
```

**c)** Filtre e exiba os **nomes dos candidatos aprovados** (IDH >= 0.65 **E** idade < 45);  
**d)** Exiba a **média de IDH** dos candidatos aprovados.

In [6]:
# Questão 2 — Parte A
quartos = np.arange(1, 13)

# a) Reshape para matriz 3x4
quartos_mtz = quartos.reshape(3, 4)
print(quartos_mtz)


# b) Soma de cada andar (linhas) e cada coluna
soma_andares = quartos_mtz.sum(axis=1)
soma_colunas = quartos_mtz.sum(axis=0)

print("Soma de cada andar (linhas):", soma_andares)
print("Soma de cada coluna:", soma_colunas) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Soma de cada andar (linhas): [10 26 42]
Soma de cada coluna: [15 18 21 24]


In [7]:
# Questão 2 — Parte B
nomes    = np.array(["Zé", "Maria", "Cláudio", "Lurdes", "Expedito", "Raimundo", "Fátima", "Tonho"])
idades   = np.array([38, 52, 41, 29, 47, 33, 61, 44])
idh      = np.array([0.71, 0.58, 0.80, 0.63, 0.70, 0.75, 0.55, 0.68])

# c) Nomes dos aprovados (IDH >= 0.65 E idade < 45)
aprovados = nomes[(idh >= 0.65) & (idades < 45)]
print("Nomes dos aprovados:", aprovados)


# d) Média de IDH dos aprovados
media_idh_aprovados = idh[ (idh >= 0.65) & (idades < 45) ].mean()
print(f"Média de IDH dos aprovados: {media_idh_aprovados:.2f}")

Nomes dos aprovados: ['Zé' 'Cláudio' 'Raimundo' 'Tonho']
Média de IDH dos aprovados: 0.73


# **Bloco 2 — Pandas**

### Questão 3 – O Mercadinho da Segunda Chance

O Zé das Couves conseguiu um emprego num mercadinho popular e ficou responsável pelo controle de preços. Crie duas **Series do Pandas** com os preços dos produtos em duas semanas diferentes:

- `semana1`: `{'Arroz': 5.50, 'Feijão': 8.90, 'Macarrão': 3.20, 'Sal': 1.80, 'Óleo': 7.40}`
- `semana2`: `{'Feijão': 9.50, 'Óleo': 6.80, 'Arroz': 5.90, 'Sal': 1.80, 'Macarrão': 3.50}`

**a)** Calcule e mostre o **gasto total** na semana 1 e na semana 2;  
**b)** Calcule a **variação de preço** de cada produto (semana2 - semana1);  
**c)** Mostre apenas os produtos que tiveram **aumento de preço**.

In [8]:
# Questão 3
semana1 = pd.Series({'Arroz': 5.50, 'Feijão': 8.90, 'Macarrão': 3.20, 'Sal': 1.80, 'Óleo': 7.40})
semana2 = pd.Series({'Feijão': 9.50, 'Óleo': 6.80, 'Arroz': 5.90, 'Sal': 1.80, 'Macarrão': 3.50})

# a) Gasto total em cada semana
gasto_semana1 = semana1.sum()
gasto_semana2 = semana2.sum()


# b) Variação de preço de cada produto
varia_preco = semana2 - semana1
print(f"Variação de preço de cada produto:{varia_preco}")

# c) Produtos com aumento de preço
aumento_preco = varia_preco[varia_preco > 0]
print(f"Produtos com aumento de preço:{aumento_preco}")

Variação de preço de cada produto:Arroz       0.4
Feijão      0.6
Macarrão    0.3
Sal         0.0
Óleo       -0.6
dtype: float64
Produtos com aumento de preço:Arroz       0.4
Feijão      0.6
Macarrão    0.3
dtype: float64


### Questão 4 – O Grande Censo dos Assistidos

O CRAS fez um censo completo e salvou os dados no arquivo `assistidos.csv`. Carregue o arquivo e responda:

**a)** Exiba **todos os dados** e as **informações gerais** do DataFrame (`.info()`);  
**b)** Calcule a **média de renda** dos assistidos da região `"Norte"`;  
**c)** Mostre o **nome e a renda** do assistido com a **maior renda**;  

In [9]:
# Questão 4 — Carregamento do CSV
df = pd.read_csv("assistidos.csv")

# a) Imprima os dados e info
print(df)
print(df.info())

                nome  idade  renda  filhos regiao  \
0      Zé das Couves     42    180       3  Norte   
1     Maria Sem Teto     55    320       1    Sul   
2    Cláudio Papelão     38      0       4  Norte   
3        Dona Lurdes     29    450       2  Leste   
4      Expedito Fome     47     90       5    Sul   
5   Raimundo Calçada     33    280       0  Oeste   
6      Fátima Brechó     61    510       2  Leste   
7  Tonho da Pracinha     44    150       3  Norte   
8  Gertrudes Marmita     36    200       1    Sul   
9      Seu Valdomiro     58     75       6  Oeste   

                  habilidade_secreta  
0            Encontrar moeda no chão  
1           Prever chuva pelo joelho  
2           Fazer castelo de papelão  
3          Pechinchar até em funeral  
4           Comer 12 pães de uma vez  
5             Dormir em pé no ônibus  
6       Achar roupa de grife no lixo  
7         Imitar qualquer passarinho  
8        Fazer sopa de pedra gourmet  
9  Contar história que nin

In [ ]:
# b) Média de renda da região Norte
media_norte = df[df['regiao'] == 'Norte']['renda'].mean()
print(f"Média de renda da região Norte: {media_norte:.2f}")

Média de renda da região Norte: 110.00


In [17]:
# c) Nome e renda do assistido com maior renda
idx_maior = df['renda'].idxmax()
nome_top = df.loc[idx_maior, 'nome']
renda_top = df.loc[idx_maior, 'renda']

print(f"Maior renda: {nome_top} com R$ {renda_top:.2f}")


Maior renda: Fátima Brechó com R$ 510.00


### Questão 5 – Relatório Final: Zé Chega ao Topo

Usando o DataFrame `df` carregado na Questão 4:

**a)** Agrupe os assistidos por **região** e mostre a **média de idade** de cada região;  
**b)** Agrupe por **região** e mostre o **número de assistidos** por região;  
**c)** Mostre a região com o **maior número de assistidos**;  

> *Parabéns! Você chegou ao fim da Operação Nova Chance. O Zé das Couves agradece e promete devolver a carteira se um dia achar a sua.*

In [ ]:
# Questão 5
# a) Média de idade por região (groupby)
media_idade_regiao = df.groupby('regiao')['idade'].mean()
print(f"Média de idade por região:\n{media_idade_regiao}")


Média de idade por região:
regiao
Leste    45.000000
Norte    41.333333
Oeste    45.500000
Sul      46.000000
Name: idade, dtype: float64


In [23]:
# b) Número de assistidos por região
assistidos_por_regiao = df['regiao'].value_counts()
print(f"Número de assistidos por região:\n{assistidos_por_regiao}")


Número de assistidos por região:
regiao
Norte    3
Sul      3
Leste    2
Oeste    2
Name: count, dtype: int64


In [24]:
# c) Região com maior número de assistidos
mais_assistidos = assistidos_por_regiao.idxmax()
print(f"Região com maior número de assistidos: {mais_assistidos}")


Região com maior número de assistidos: Norte


# Fim da Lista — Operação Nova Chance

> *"Todo mendigo já foi alguém que não entregou as listas a tempo."*  
> — Prof. Ruan Patrick, em um momento de reflexão existencial
---
*Inatel – Instituto Nacional de Telecomunicações*  
*Disciplina: Ciência de Dados com Python*