# Ciência de Dados com Python – Cap. 4: Introdução ao NumPy
## Exercícios Práticos

**Disciplina:** Ciência de Dados com Python (C11)  
**Instituição:** Inatel – Instituto Nacional de Telecomunicações  
**Prof.:** Renzo Paranaíba Mesquita

---

In [ ]:
# Importação da biblioteca (execute esta célula antes de começar)
import numpy as np

---
## Exercícios – Parte 1
---

### Exercício 1

Crie dois NumPy Arrays unidimensionais de tamanho **8**: um formado apenas por **1's** e outro formado por **números aleatórios entre 0 e 9**. Some estes dois NumPy Arrays e guarde o resultado dentro de um terceiro NumPy Array. Por fim, faça o seguinte:

**a)** Se a soma de todos os elementos do Array resultante for **>= 40**, remodele este NumPy Array para se tornar uma **matriz com mais linhas do que colunas**. Senão, remodele para que se torne uma **matriz com mais colunas do que linhas**.

In [ ]:
# Resolução do Exercício 1
import numpy as np
arr1 = np.ones(8)
arr2 = np.random.randint(0, 10, 8)
arr3 = arr1 + arr2
print(arr1)
print(arr2)
print(arr3)
print("-"*70)

soma_total = arr3.sum()
print(f"Soma total dos elementos: {soma_total}")

if soma_total >= 40:
    matriz = arr3.reshape(4, 2)
    formato = "4x2"
else:
    matriz = arr3.reshape(2, 4)
    formato = "2x4"

print(f"Formato escolhido: {formato}")
print("Matriz Resultante:")
print(matriz)




[1. 1. 1. 1. 1. 1. 1. 1.]
[1 5 6 5 7 3 8 8]
[2. 6. 7. 6. 8. 4. 9. 9.]
----------------------------------------------------------------------
Soma total dos elementos: 51.0
Formato escolhido: 4x2 (Mais linhas que colunas)
Matriz Resultante:
[[2. 6.]
 [7. 6.]
 [8. 4.]
 [9. 9.]]


### Exercício 2

Crie dois NumPy Arrays unidimensionais: um de **números pares de 0 a 51** e outro também de **números pares de 100 até 50**. Em seguida, os **concatene** e mostre os resultados **ordenados**.

In [5]:
# Resolução do Exercício 2
import numpy as np
arr1 = np.arange(0, 52, 2)
arr2 = np.arange(100, 49, -2)
resultado = np.sort(np.concatenate((arr1, arr2)))
print("concatenados:", resultado)


concatenados: [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  50  52  54  56  58  60  62  64  66  68
  70  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### Exercício 3 – Mini Campo Minado

**a)** Crie um NumPy Array **2x2** formado apenas por **0's**

**b)** Em seguida, adicione o número **1** em uma **posição aleatória** desta matriz

**c)** Faça uma entrada de dados para solicitar o usuário que faça uma jogada (selecione uma posição da matriz):

- **I.** Se ele selecionar todas as posições em que o número 1 **não** se encontra, mostre a mensagem: *"Congratulations! You beat the game! :)"*
- **II.** Senão, se dentro das **3 primeiras jogadas** ele achar o número 1, mostre a mensagem: *"Game Over! :( Try Again!"*

In [ ]:
# Resolução do Exercício 3
import numpy as np
mtz = np.zeros([2,2])
lin = np.random.randint(0, 1)
col = np.random.randint(0, 1)
mtz[lin, col] = 1

tentativas = 0
vitoria = True

while tentativas < 3:
    print(f"\nJogada {tentativas + 1}:")
    escolha_lin = int(input("Linha (0 ou 1): "))
    escolha_col = int(input("Coluna (0 ou 1): "))
    
    if mtz[escolha_lin, escolha_col] == 1:
        print("Game Over! :( Try Again!")
        vitoria = False
        break
    else:
        print("Safe.")
        tentativas += 1

if vitoria:
    print("Congratulations! You beat the game! :)")



Jogada 1:


### Exercício 4

Crie uma matriz de **tamanho qualquer**. Extraia seu **número de linhas e colunas**, multiplique-os, e diga se esta matriz poderia se tornar um vetor unidimensional com número **par** ou **ímpar** de elementos.

In [ ]:
# Resolução do Exercício 4


### Exercício 5

Crie uma matriz de tamanho **4x4** formada por **números aleatórios inteiros entre 1 e 50** (use `seed = 10` antes).

**a)** Mostre o resultado da **média de cada linha** e **cada coluna** da matriz gerada.

**b)** Apresente o **maior valor** das médias das linhas e também das colunas.

**c)** Mostre a **quantidade de aparições** de cada um dos números gerados na matriz. Em seguida, mostre apenas os números que aparecem **2 vezes**.

In [ ]:
# Resolução do Exercício 5a


In [ ]:
# Resolução do Exercício 5b


In [ ]:
# Resolução do Exercício 5c
