# Ciência de Dados com Python – Cap. 4: NumPy
##  Exercícios Práticos

**Disciplina:** Ciência de Dados com Python (C11)  
**Instituição:** Inatel – Instituto Nacional de Telecomunicações  
**Prof.:** Ruan Patrick de Souza

---

Todos os exercícios utilizam o dataset **`cidades_brasil.csv`**, que contém informações sobre 25 cidades brasileiras.

```
Índice | Coluna      | Descrição
-------|-------------|----------------------------------
  0    | cidade      | Nome da cidade
  1    | estado      | Sigla do estado
  2    | populacao   | População estimada
  3    | area_km2    | Área em km²
  4    | idh         | Índice de Desenvolvimento Humano
  5    | regiao      | Região do Brasil
  6    | fundacao    | Ano de fundação
```

In [1]:
# Importação e carregamento do dataset
import numpy as np

dados = np.loadtxt('cidades_brasil.csv', delimiter=',', dtype=str, skiprows=1)

# Colunas textuais
cidades    = dados[:, 0]
estados    = dados[:, 1]
regioes    = dados[:, 5]

# Colunas numéricas
populacao  = dados[:, 2].astype(int)
area       = dados[:, 3].astype(int)
idh        = dados[:, 4].astype(float)
fundacao   = dados[:, 6].astype(int)

print(f"Dataset carregado: {len(cidades)} cidades")
print(dados)

Dataset carregado: 25 cidades
[['Sao Paulo' 'SP' '12325232' '1521' '0.805' 'Sudeste' '1554']
 ['Rio de Janeiro' 'RJ' '6748000' '1200' '0.799' 'Sudeste' '1565']
 ['Brasilia' 'DF' '3055149' '5802' '0.824' 'Centro-Oeste' '1960']
 ['Salvador' 'BA' '2886698' '693' '0.759' 'Nordeste' '1549']
 ['Fortaleza' 'CE' '2703391' '314' '0.754' 'Nordeste' '1726']
 ['Belo Horizonte' 'MG' '2530701' '331' '0.810' 'Sudeste' '1897']
 ['Manaus' 'AM' '2255903' '11401' '0.737' 'Norte' '1669']
 ['Curitiba' 'PR' '1963726' '435' '0.823' 'Sul' '1693']
 ['Recife' 'PE' '1661681' '218' '0.772' 'Nordeste' '1537']
 ['Goiania' 'GO' '1555626' '739' '0.799' 'Centro-Oeste' '1933']
 ['Belem' 'PA' '1506420' '1065' '0.746' 'Norte' '1616']
 ['Porto Alegre' 'RS' '1492530' '497' '0.805' 'Sul' '1772']
 ['Guarulhos' 'SP' '1404694' '318' '0.763' 'Sudeste' '1560']
 ['Campinas' 'SP' '1223237' '795' '0.805' 'Sudeste' '1774']
 ['Sao Luis' 'MA' '1115932' '827' '0.768' 'Nordeste' '1612']
 ['Maceio' 'AL' '1025360' '510' '0.721' 'Nordeste'

---
### Exercício 1 – Propriedades e Criação de Arrays

**a)** Exiba as propriedades `size`, `ndim` e `shape` do array `populacao`.

**b)** Crie um array de **zeros** com o mesmo tamanho do array `populacao`. Em seguida, substitua seus valores pela população dividida por **1000** (população em milhares).

**c)** Crie um array usando `np.arange` que represente os **índices** (0, 1, 2, ...) de cada cidade no dataset. Exiba o array.

In [2]:
# Resolução do Exercício 1
print(f"O arquivo possui {dados.size} topicos")
print(f"{dados.ndim} dimensoes")
print(f"na escala de {dados.shape}")
print(f"População: {populacao}")
print("_"*70)

zeros = np.zeros(populacao.size)
print(f"{zeros}\n")
calculoPopulacao = zeros + (populacao/1000)
print(f"População em milhares:\n {calculoPopulacao}")
print("_"*70)

indexCidades = np.arange(cidades.size)
print(f"index das cidades : {indexCidades}")



O arquivo possui 175 topicos
2 dimensoes
na escala de (25, 7)
População: [12325232  6748000  3055149  2886698  2703391  2530701  2255903  1963726
  1661681  1555626  1506420  1492530  1404694  1223237  1115932  1025360
   916001   896708   871126   833932   516524   365855   433656    44686
    74824]
______________________________________________________________________
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]

População em milhares:
 [12325.232  6748.     3055.149  2886.698  2703.391  2530.701  2255.903
  1963.726  1661.681  1555.626  1506.42   1492.53   1404.694  1223.237
  1115.932  1025.36    916.001   896.708   871.126   833.932   516.524
   365.855   433.656    44.686    74.824]
______________________________________________________________________
index das cidades : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


---
### Exercício 2 – Operações Estatísticas

**a)** Calcule e exiba a **média**, o **mínimo** e o **máximo** da população. Mostre também o **nome** da cidade mais populosa e da menos populosa (use `argmax` e `argmin`).

Dica: Caso necessário, para converter dados numéricos que estão como texto no array, você pode fazer a chamada da função `populacao  = dados[:, 2].astype(int)` colocando a tipagem no parêntezes (Ex: `int`, `float`)

**b)** Calcule e exiba a **soma total** das áreas de todas as cidades e a **média** do IDH do dataset.

**c)** Encontre o **índice** da cidade mais antiga (menor ano de fundação) e o **índice** da mais recente. Exiba os nomes e anos correspondentes.

In [3]:
# Resolução do Exercício 2

print(f"Media: {populacao.mean()} ")
print(f"Minimo: {populacao.min()}")
print(f"Maximo: {populacao.max()}")
idx_max = populacao.argmax()
idx_min = populacao.argmin()
print(f"Cidade mais populosa: {cidades[idx_max]}")
print(f"Cidade menos populosa: {cidades[idx_min]}")
print("_"*70)

soma_total = np.sum(area)
print(f"a soma total da area : {soma_total}\n")
media_idh = np.sum(idh)/idh.size
print(f"A media do idg das cidades : {media_idh}")
print("_"*70)

mais_antiga_idx = fundacao.argmax()
menos_antiga_idx = fundacao.argmin()

print(f"a cidade mais antiga : {cidades[mais_antiga_idx]} fundada no ano {fundacao.min()}")
print(f"a cidade mais nova : {cidades[menos_antiga_idx]} fundada no ano {fundacao.max()}")



Media: 2016303.68 
Minimo: 44686
Maximo: 12325232
Cidade mais populosa: Sao Paulo
Cidade menos populosa: Santa Rita do Sapucai
______________________________________________________________________
a soma total da area : 39178

A media do idg das cidades : 0.7817999999999999
______________________________________________________________________
a cidade mais antiga : Brasilia fundada no ano 1537
a cidade mais nova : Recife fundada no ano 1960


---
### Exercício 3 – Operações entre Arrays e Broadcasting

**a)** Calcule a **densidade demográfica** (população / área) de cada cidade e armazene em um novo array. Exiba as 5 cidades com **maior** densidade (exiba nome e valor).

**b)** Calcule a **idade** de cada cidade (2025 - ano de fundação) usando broadcasting. Exiba o array resultante.

**c)** Crie um array de **1's** com o mesmo tamanho que `idh`. Multiplique-o por **1000** e depois **some** com o array `idh * 1000` (IDH em escala de milésimos). Exiba o resultado.

In [ ]:
# Resolução do Exercício 3
densidade_demografica = populacao / area
arr = np.array(np.argsort(densidade_demografica)[-5:])
print(f"cidades com maior densidade demografica {cidades[arr]}")
print("_"*70)

idade_das_cidades = 2025 - fundacao
print(f"Idade das cidades : {idade_das_cidades}")
print("_"*70)

array_de_uns = np.ones(idh.size*1000)
idh_milesimos = array_de_uns  + (idh.size * 1000) 
print(f"IDH em escala de milesimos: {idh_milesimos}")


cidades com maior densidade demografica ['Rio de Janeiro' 'Recife' 'Belo Horizonte' 'Sao Paulo' 'Fortaleza']
______________________________________________________________________
Idade das cidades : [471 460  65 476 299 128 356 332 488  92 409 253 465 251 413 210 126 426
 173 440 299 474 479 145 314]
______________________________________________________________________
IDH em escala de milesimos: [25001. 25001. 25001. ... 25001. 25001. 25001.]


---
### Exercício 4 – Concatenação e Ordenação

**a)** Separe o array `populacao` em dois: um com as **10 primeiras** cidades e outro com as **10 últimas**. Concatene-os em um único array e exiba.

**b)** Ordene o array `idh` em ordem crescente usando `np.sort` e exiba. Qual é o menor e o maior IDH após a ordenação?

**c)** Use `np.argsort` no array `populacao` para obter os **índices** que ordenariam as cidades por população. Exiba os nomes das **5 cidades menos populosas** usando esses índices.

In [30]:
# Resolução do Exercício 4
populacao1 = populacao[:10]
populacao2 = populacao[-10:]
print(populacao1)
print(populacao2)
concatenados = np.concatenate((populacao1 , populacao2))
print(f"O novo array com 20 cidades: {concatenados}")
print("_"*70)

idh_ordenado = np.sort(idh)
maior_idh = idh_ordenado.argmax()
menor_idh = idh_ordenado.argmin()
print(f"A cidade com maior IDH e : {cidades[maior_idh]} com {idh_ordenado.max()}")
print(f"A cidade com menor IDH e : {cidades[menor_idh]} com {idh_ordenado.min()}")
print("_"*70)

populacao_idx = np.argsort(populacao)[:5]
print(f"as 5 cidades menos populosas são :{cidades[populacao_idx]}")


[12325232  6748000  3055149  2886698  2703391  2530701  2255903  1963726
  1661681  1555626]
[1025360  916001  896708  871126  833932  516524  365855  433656   44686
   74824]
O novo array com 20 cidades: [12325232  6748000  3055149  2886698  2703391  2530701  2255903  1963726
  1661681  1555626  1025360   916001   896708   871126   833932   516524
   365855   433656    44686    74824]
______________________________________________________________________
A cidade com maior IDH e : Ouro Preto com 0.847
A cidade com menor IDH e : Sao Paulo com 0.721
______________________________________________________________________
as 5 cidades menos populosas são :['Santa Rita do Sapucai' 'Ouro Preto' 'Vitoria' 'Santos' 'Florianopolis']


---
### Exercício 5 – Reshape e Matrizes

**a)** Crie uma **matriz numérica** empilhando `populacao`, `area` e `fundacao` como colunas (use `np.column_stack`). Exiba as propriedades `shape`, `ndim` e `size`.

**b)** Extraia da matriz apenas a **coluna de área** (coluna de índice 1) e exiba.

**c)** Selecione as **5 primeiras linhas** e as **2 primeiras colunas** da matriz (fatiamento). Exiba o resultado e os nomes das cidades correspondentes.

In [42]:
# Resolução do Exercício 5
mtz_empilhada = np.column_stack((populacao,area,fundacao))
print(f"{mtz_empilhada}\n")
print(mtz_empilhada.size)
print(mtz_empilhada.shape)
print(mtz_empilhada.ndim)
print("_"*70)

coluna_area = mtz_empilhada[:, 1].astype(int)
print(f"a coluna de area:{coluna_area}")
print("_"*70)

cinco_primeiras_linhas =  mtz_empilhada[0:5]
duas_primeiras_colunas = mtz_empilhada[:, :2]

print(f"As 5 primeiras linhas{cinco_primeiras_linhas}")
print(f"As 2 primeiras colunas{duas_primeiras_colunas}")

[[12325232     1521     1554]
 [ 6748000     1200     1565]
 [ 3055149     5802     1960]
 [ 2886698      693     1549]
 [ 2703391      314     1726]
 [ 2530701      331     1897]
 [ 2255903    11401     1669]
 [ 1963726      435     1693]
 [ 1661681      218     1537]
 [ 1555626      739     1933]
 [ 1506420     1065     1616]
 [ 1492530      497     1772]
 [ 1404694      318     1560]
 [ 1223237      795     1774]
 [ 1115932      827     1612]
 [ 1025360      510     1815]
 [  916001     8093     1899]
 [  896708      167     1599]
 [  871126     1392     1852]
 [  833932      211     1585]
 [  516524      675     1726]
 [  365855       98     1551]
 [  433656      281     1546]
 [   44686      350     1880]
 [   74824     1245     1711]]

75
(25, 3)
2
______________________________________________________________________
a coluna de area:[ 1521  1200  5802   693   314   331 11401   435   218   739  1065   497
   318   795   827   510  8093   167  1392   211   675    98   281   350
 

---
### Exercício 6 – Fatiamento no Dataset

**a)** Exiba os nomes e populações das cidades de **índice 5 a 9** (5 cidades).

**b)** Exiba os nomes e o IDH das **últimas 3 cidades** do dataset.

**c)** Exiba os dados de todas as cidades **de 2 em 2** (índice 0, 2, 4, ...), mostrando nome e região.

In [ ]:
# Resolução do Exercício 6

print(f"Cidades 5 a 9: {cidades[5:10]}")
print(f"Populações 5 a 9: {populacao[5:10]}")
print("_"*70)

print(f"Nomes das ultimas 3: {cidades[-3:]}")
print(f"IDH das ultimas 3: {idh[-3:]}")
print("_"*70)

print(f"Cidades de 2 em 2: {cidades[::2]}")
print(f"Regiões de 2 em 2: {regioes[::2]}")
print("_"*70)

Cidades 5 a 9: ['Belo Horizonte' 'Manaus' 'Curitiba' 'Recife' 'Goiania']
Populações 5 a 9: [2530701 2255903 1963726 1661681 1555626]
______________________________________________________________________
Nomes das últimas 3: ['Santos' 'Santa Rita do Sapucai' 'Ouro Preto']
IDH das últimas 3: [0.84  0.721 0.741]
______________________________________________________________________
Cidades de 2 em 2: ['Sao Paulo' 'Brasilia' 'Fortaleza' 'Manaus' 'Recife' 'Belem' 'Guarulhos'
 'Sao Luis' 'Campo Grande' 'Teresina' 'Florianopolis' 'Santos'
 'Ouro Preto']
Regiões de 2 em 2: ['Sudeste' 'Centro-Oeste' 'Nordeste' 'Norte' 'Nordeste' 'Norte' 'Sudeste'
 'Nordeste' 'Centro-Oeste' 'Nordeste' 'Sul' 'Sudeste' 'Sudeste']
______________________________________________________________________


---
### Exercício 7 – Filtros Condicionais

**a)** Filtre e exiba os nomes das cidades com **população maior que 2 milhões**.

**b)** Filtre e exiba os nomes das cidades com **IDH maior ou igual a 0.80** que foram **fundadas antes de 1700**.

**c)** Filtre e exiba os nomes das cidades da região **Nordeste** com **área menor que 500 km²**.

In [ ]:
# Resolução do Exercício 7


---
### Exercício 8 – Elementos Únicos e Contagem

**a)** Descubra quais são as **regiões únicas** do dataset e quantas cidades pertencem a cada uma (use `np.unique` com `return_counts=True`).

**b)** Descubra quais são os **estados únicos** e quantas cidades cada estado possui no dataset.

**c)** Exiba qual é a **região com mais cidades** e qual é o **estado com mais cidades** no dataset.

In [ ]:
# Resolução do Exercício 8


---
### Exercício 9 – Manipulação de Texto com `np.char`

**a)** Converta todos os nomes de cidades para **letras maiúsculas** e exiba.

**b)** Verifique quais cidades **começam** com a letra `"S"` e exiba seus nomes. Faça o mesmo para cidades que **começam** com `"B"`.

**c)** Encontre o **índice** (posição) da substring `"do"` em cada nome de cidade. Exiba apenas as cidades onde a substring foi encontrada (índice diferente de -1).

In [ ]:
# Resolução do Exercício 9


---
### Exercício 10 – Persistência de Dados

**a)** Crie uma matriz com as colunas `populacao` e `idh` (use `np.column_stack`). Salve-a em um arquivo de texto **`pop_idh.txt`** usando `np.savetxt` (use `fmt='%.3f'` para manter as casas decimais do IDH).

**b)** Salve o array `fundacao` em um arquivo binário **`fundacao_cidades.npy`** usando `np.save`.

**c)** Carregue ambos os arquivos (`np.loadtxt` e `np.load`) e exiba os dados para confirmar que foram salvos corretamente.

In [ ]:
# Resolução do Exercício 10
