# Ciência de Dados com Python – Cap. 4: NumPy
## Exercícios Práticos

**Disciplina:** Ciência de Dados com Python (C11)  
**Instituição:** Inatel – Instituto Nacional de Telecomunicações  
**Prof.:** Ruan Patrick de Souza

---

In [2]:
# Importação da biblioteca
import numpy as np

---
## Parte 1 – Arrays, Operações, Reshape e Aleatórios
---

### Exercício 1 – Criação e Operações Básicas

**a)** Crie um NumPy Array com os números inteiros de **10 a 50** (inclusive), com passo de **5**.

**b)** Crie um segundo Array de mesmo tamanho, formado apenas por **2's**.

**c)** Multiplique os dois arrays elemento a elemento e armazene o resultado em um terceiro array.

**d)** Exiba o **valor mínimo**, o **valor máximo**, a **soma** e a **média** do array resultante.

In [6]:
# Resolução do Exercício 1
arr = np.arange(10, 51, 5)
print(arr)
arr2 = np.array([2,2,2,2,2,2,2,2,2])
print(arr2)

arr3 = arr * arr2
print(arr3)

print(arr3.min(), arr3.max(), arr3.sum(), arr3.mean())


[10 15 20 25 30 35 40 45 50]
[2 2 2 2 2 2 2 2 2]
[ 20  30  40  50  60  70  80  90 100]
20 100 540 60.0


### Exercício 2 – Concatenação e Ordenação

**a)** Crie um Array com os números **ímpares de 1 a 19** (usando `np.arange`).

**b)** Crie outro Array com **5 números inteiros aleatórios entre 20 e 50** (use `np.random.seed(10)` para reprodutibilidade).

**c)** Concatene os dois arrays em um único array.

**d)** Exiba o array concatenado **ordenado em ordem crescente** (pesquise a função `np.sort`).

In [18]:
# Resolução do Exercício 2
arr = np.arange(1,20,2)
print(arr)

np.random.seed(10)
arr2 = np.random.randint(20,51,5)
print(arr2)

arrConc = np.concatenate((arr, arr2)) 

print(np.sort(arrConc))


[ 1  3  5  7  9 11 13 15 17 19]
[29 49 24 35 20]
[ 1  3  5  7  9 11 13 15 17 19 20 24 29 35 49]


### Exercício 3 – Reshape e Propriedades

**a)** Crie um Array com **12 números inteiros aleatórios entre 1 e 100** (use `np.random.seed(25)`).

**b)** Exiba as propriedades: **tamanho** (`size`), **número de dimensões** (`ndim`) e **formato** (`shape`).

**c)** Remodele (`reshape`) este array para uma **matriz 3×4**.

**d)** Remodele novamente para uma **matriz 4×3** e exiba as propriedades atualizadas.

**e)** Aplique **broadcasting** para multiplicar toda a matriz por **10** e exiba o resultado.

In [ ]:
# Resolução do Exercício 3
np.random.seed(25)
arr = np.random.randint(1,101,12)
print(arr)
print(arr.size)   
print(arr.ndim)  
print(arr.shape)

mtz = arr.reshape(3, 4)
print(mtz)
print("-"*70)
newMtz = mtz.reshape(4,3)
print(newMtz)
print("-"*70)

print(newMtz*10)


[ 5 63 91 16 62 24 45 51  9 29  5 90]
12
1
(12,)
[[ 5 63 91 16]
 [62 24 45 51]
 [ 9 29  5 90]]
----------------------------------------------------------------------
[[ 5 63 91]
 [16 62 24]
 [45 51  9]
 [29  5 90]]
----------------------------------------------------------------------
[[ 50 630 910]
 [160 620 240]
 [450 510  90]
 [290  50 900]]


### Exercício 4 – Aleatórios e Elementos Únicos

**a)** Gere um Array com **20 números inteiros aleatórios entre 1 e 10** (use `np.random.seed(7)`).

**b)** Descubra quais são os **elementos únicos** deste array e suas respectivas **frequências**.

**c)** Exiba qual é o **elemento que mais se repete** e quantas vezes ele aparece.

**d)** Exiba o **índice do maior valor** e o **índice do menor valor** do array original.

In [25]:
# Resolução do Exercício 4
np.random.seed(7)
arr = np.random.randint(1,11,20)
print(arr)
print(np.unique(arr))
print(np.unique(arr, return_counts=True))
print(arr.argmax(),arr.argmin())



[ 5 10  7  4  4  8  8 10  8  9 10  9  8  7  5  1  8  1  8  7]
[ 1  4  5  7  8  9 10]
(array([ 1,  4,  5,  7,  8,  9, 10], dtype=int32), array([2, 2, 2, 3, 6, 2, 3]))
1 15


---
## Parte 2 – Fatiamento, Filtros, Texto e Persistência
---

### Exercício 5 – Fatiamento de Matrizes

Considere a seguinte matriz:

```
mtz = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
```

Utilizando **fatiamento** (slicing), extraia e exiba:

**a)** A **segunda linha** completa.

**b)** A **terceira coluna** (todos os elementos da coluna de índice 2).

**c)** A **submatriz** formada pelas **duas primeiras linhas** e **duas últimas colunas**.

**d)** O **elemento** da linha 2, coluna 3 (índices 1 e 2).

In [31]:
# Resolução do Exercício 5
mtz = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print(mtz[1])  
print("-"*70)
print(mtz[:, 2])
print("-"*70)
print(mtz[1,2])


[50 60 70 80]
----------------------------------------------------------------------
[ 30  70 110]
----------------------------------------------------------------------
70


### Exercício 6 – Filtros Condicionais

**a)** Crie uma **matriz 4×5** com **20 números inteiros aleatórios entre 1 e 50** (use `np.random.seed(15)`).

**b)** Utilizando **indexação booleana**, filtre e exiba apenas os elementos **maiores que 25**.

**c)** Filtre e exiba apenas os elementos **pares** da matriz.

**d)** Filtre e exiba os elementos que sejam **maiores que 10 E menores que 40** ao mesmo tempo.

In [ ]:
# Resolução do Exercício 6
np.random.seed(15)
mtz = np.random.randint(1, 51, [4, 5])
print(mtz)
print("-"*70)
print(mtz > 25)
print("-"*70)

cond = mtz % 2 == 0
print(mtz[cond])  
print("-"*70)

print(mtz >10 and mtz < 40)


[[ 9 13  6  1 29]
 [28  8 12 22 48]
 [30 18 46 32 24]
 [33 11 16  5 42]]
----------------------------------------------------------------------
[[False False False False  True]
 [ True False False False  True]
 [ True False  True  True False]
 [ True False False False  True]]
----------------------------------------------------------------------
[ 6 28  8 12 22 48 30 18 46 32 24 16 42]
----------------------------------------------------------------------


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Exercício 7 – Manipulação de Texto com `np.char`

Considere o seguinte array de nomes de cidades:

```
cidades = np.array(['São Paulo', 'Rio de Janeiro', 'Belo Horizonte',
                     'Santa Rita do Sapucaí', 'Salvador', 'Curitiba'])
```

**a)** Converta todos os nomes para **letras maiúsculas**.

**b)** Verifique quais cidades **começam** com a letra `"S"`.

**c)** Encontre o **índice** (posição) da substring `"de"` em cada nome. Se não existir, o resultado será `-1`.

**d)** Verifique quais nomes contêm **apenas letras** (sem espaços ou caracteres especiais).

In [43]:
# Resolução do Exercício 7
cidades = np.array(['São Paulo', 'Rio de Janeiro', 'Belo Horizonte',
                     'Santa Rita do Sapucaí', 'Salvador', 'Curitiba'])

arr = np.char.upper(cidades)
print(arr)
print("-"*70)

arr2 = np.char.startswith(arr, 'S')
print(arr2)
print("-"*70)

indices_de = np.char.find(cidades, 'de')
print(indices_de)
print("-"*70)

apenas_letras = np.char.isalpha(np.char.replace(cidades, ' ', '')) 
apenas_letras_rigoroso = np.char.isalpha(cidades)
print(apenas_letras_rigoroso)



['SÃO PAULO' 'RIO DE JANEIRO' 'BELO HORIZONTE' 'SANTA RITA DO SAPUCAÍ'
 'SALVADOR' 'CURITIBA']
----------------------------------------------------------------------
[ True False False  True  True False]
----------------------------------------------------------------------
[-1  4 -1 -1 -1 -1]
----------------------------------------------------------------------
[False False False False  True  True]


### Exercício 8 – Persistência de Dados

**a)** Crie uma **matriz 5×3** com **15 números inteiros aleatórios entre 0 e 100** (use `np.random.seed(50)`).

**b)** Salve essa matriz em um **arquivo de texto** chamado `dados.txt` (usando `np.savetxt`). 

**c)** Carregue ambos os arquivos (`np.loadtxt` e `np.load`) e exiba os dados carregados para confirmar que foram salvos corretamente.

In [49]:
# Resolução do Exercício 8
np.random.seed(50)
mtz = np.random.randint(0, 101, [5, 3])
print(mtz)
print("_"*70)
np.savetxt('dados.txt', mtz)
dataset_carregado = np.loadtxt('dados.txt')
print(dataset_carregado)


[[48 96 11]
 [33 94  4]
 [70 70 22]
 [ 5  2 95]
 [71 68 78]]
______________________________________________________________________
[[48. 96. 11.]
 [33. 94.  4.]
 [70. 70. 22.]
 [ 5.  2. 95.]
 [71. 68. 78.]]
